# Nama workflow
name: OpenWRT ZTE E8820S Build

# Memicu workflow secara manual melalui UI GitHub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenWRT
    steps:
    # 1. Menyiapkan environment build
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-setuptools python3-dev rsync unzip zlib1g-dev file wget

    
    # 2. Mengunduh source code OpenWRT dan patch
    # REKOMENDASI: Ganti 'v19.07.10' dengan versi lebih baru seperti 'v23.05.4'
    # Peringatan: Patch di bawah ini kemungkinan tidak akan berfungsi dengan OpenWRT versi baru.
    - name: Clone OpenWRT and device patch
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v19.07.10  # <-- SANGAT DISARANKAN UNTUK DIGANTI
        cd ..
        git clone https://github.com/srt19/ZTE-E8820S.git

    # 3. Menerapkan patch untuk dukungan ZTE E8820S
    - name: Apply patch for ZTE E8820S
      run: |
        # Menyalin file target device dan package
        cp -r ZTE-E8820S/target/linux/ramips openwrt/target/linux/
        cp -r ZTE-E8820S/package/* openwrt/package/

    # 4. Mempersiapkan konfigurasi build
    - name: Setup build configuration
      run: |
        # Menggunakan file .config dari repository Anda
        cp config.buildinfo openwrt/.config
        cd openwrt
        make defconfig

    # 5. Kompilasi firmware
    - name: Build firmware
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # Menggunakan -j(nproc) untuk mempercepat kompilasi
        make -j$(nproc)

    # 6. Mengunggah firmware yang sudah jadi sebagai artefak
    # KESALAHAN DIPERBAIKI: Menggunakan @v4 dan path yang benar
    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-19.07-zte-e8820s-firmware
        path: openwrt/bin/targets/ramips/mt7621/*.bin
